[package]
name = "requiem"
version = "0.0.1"
authors = ["Agora DAO <mark@gold.com>"]
edition = "2021"

[profile.dev]
opt-level = 3

[features]
default = []
ethereum = ["ethers"]

[dependencies]
anyhow = "1"
async-trait = "0.1"
boolean_expression = "0.4.4"
ethers = { version = "0.17.0", optional = true }
futures = { version = "0.3.24", default-features = false }
reqwest = { version = "0.11.11", features = ["json"] }
thiserror = "1"
